---
# This should work on Ansible >2.2

# First, Do all of the provisioning and add the hosts to in-memory inventory
- hosts: all
  gather_facts: false
  connection: local
  #vars:
  #  ansible_python_interpreter: "{{ansible_playbook_python}}"

  tasks:
#  - name: "INCLUDES | Include vaulted credentials"
#    include_vars: group_vars/vaulted.yml
#    no_log: true
  - name: Informacion de los datastores
    vmware_datastore_facts:
     cluster: ECL-PVMWARE01-HVD
     validate_certs: no
    delegate_to: localhost
    register: facts
  - debug:
      msg: "{{ item }}"
    loop: "{{ facts.datastores }}"
    #no_log: True
