---
# This should work on Ansible >2.2

# First, Do all of the provisioning and add the hosts to in-memory inventory
- hosts: all
  gather_facts: false
  connection: local
  #vars:
  #  ansible_python_interpreter: "{{ansible_playbook_python}}"

  tasks:
#  - name: "INCLUDES | Include vaulted credentials"
#    include_vars: group_vars/vaulted.yml
#    no_log: true
  - name: "APROVISIONAMIENTO | Crear VM desde plantilla"
    vmware_guest:
      validate_certs: "no"
      datacenter: "{{ datacenter }}"
      name: "{{ item.nombre }}"
      folder: "{{ folder }}"
      template: "{{ vmtemplate }}"
      state: poweredon
      annotation: '{{ vmnotes|default("") }}'
      cluster: "{{ cluster }}"
      hardware:
        num_cpus: "{{ item.cpu }}"
        memory_mb: "{{ item.mem_mb }}"
      disk:
      - size_gb: "100"
        type: thin
        datastore: "{{ datastore }}"
      networks:
      - name: "{{ port_grp }}"
        type: "static"
        ip: "{{ item.ip }}"
        netmask: "{{ item.mascara }}"
        gateway: "{{ gateway }}"
        start_connected: yes
      wait_for_ip_address: yes
    loop: "{{ servidores }}"
#    register: new_vm
